/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthStudentsRouteImport } from './routes/_auth/students'
import { Route as AuthInstructorsRouteImport } from './routes/_auth/instructors'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthCreateCourseRouteImport } from './routes/_auth/createCourse'
import { Route as AuthCoursesRouteImport } from './routes/_auth/courses'
import { Route as AuthStudentsStudentIdRouteImport } from './routes/_auth/students_.$studentId'
import { Route as AuthInstructorsInstructorIdRouteImport } from './routes/_auth/instructors_.$instructorId'
import { Route as AuthCoursesCourseIdRouteImport } from './routes/_auth/courses_.$courseId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthStudentsRoute = AuthStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthInstructorsRoute = AuthInstructorsRouteImport.update({
  id: '/instructors',
  path: '/instructors',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCreateCourseRoute = AuthCreateCourseRouteImport.update({
  id: '/createCourse',
  path: '/createCourse',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCoursesRoute = AuthCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthStudentsStudentIdRoute = AuthStudentsStudentIdRouteImport.update({
  id: '/students_/$studentId',
  path: '/students/$studentId',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthInstructorsInstructorIdRoute =
  AuthInstructorsInstructorIdRouteImport.update({
    id: '/instructors_/$instructorId',
    path: '/instructors/$instructorId',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthCoursesCourseIdRoute = AuthCoursesCourseIdRouteImport.update({
  id: '/courses_/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/courses': typeof AuthCoursesRoute
  '/createCourse': typeof AuthCreateCourseRoute
  '/dashboard': typeof AuthDashboardRoute
  '/instructors': typeof AuthInstructorsRoute
  '/students': typeof AuthStudentsRoute
  '/courses/$courseId': typeof AuthCoursesCourseIdRoute
  '/instructors/$instructorId': typeof AuthInstructorsInstructorIdRoute
  '/students/$studentId': typeof AuthStudentsStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/courses': typeof AuthCoursesRoute
  '/createCourse': typeof AuthCreateCourseRoute
  '/dashboard': typeof AuthDashboardRoute
  '/instructors': typeof AuthInstructorsRoute
  '/students': typeof AuthStudentsRoute
  '/courses/$courseId': typeof AuthCoursesCourseIdRoute
  '/instructors/$instructorId': typeof AuthInstructorsInstructorIdRoute
  '/students/$studentId': typeof AuthStudentsStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_auth/courses': typeof AuthCoursesRoute
  '/_auth/createCourse': typeof AuthCreateCourseRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/instructors': typeof AuthInstructorsRoute
  '/_auth/students': typeof AuthStudentsRoute
  '/_auth/courses_/$courseId': typeof AuthCoursesCourseIdRoute
  '/_auth/instructors_/$instructorId': typeof AuthInstructorsInstructorIdRoute
  '/_auth/students_/$studentId': typeof AuthStudentsStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/courses'
    | '/createCourse'
    | '/dashboard'
    | '/instructors'
    | '/students'
    | '/courses/$courseId'
    | '/instructors/$instructorId'
    | '/students/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/courses'
    | '/createCourse'
    | '/dashboard'
    | '/instructors'
    | '/students'
    | '/courses/$courseId'
    | '/instructors/$instructorId'
    | '/students/$studentId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/register'
    | '/_auth/courses'
    | '/_auth/createCourse'
    | '/_auth/dashboard'
    | '/_auth/instructors'
    | '/_auth/students'
    | '/_auth/courses_/$courseId'
    | '/_auth/instructors_/$instructorId'
    | '/_auth/students_/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/students': {
      id: '/_auth/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthStudentsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/instructors': {
      id: '/_auth/instructors'
      path: '/instructors'
      fullPath: '/instructors'
      preLoaderRoute: typeof AuthInstructorsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/createCourse': {
      id: '/_auth/createCourse'
      path: '/createCourse'
      fullPath: '/createCourse'
      preLoaderRoute: typeof AuthCreateCourseRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/courses': {
      id: '/_auth/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AuthCoursesRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/students_/$studentId': {
      id: '/_auth/students_/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof AuthStudentsStudentIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/instructors_/$instructorId': {
      id: '/_auth/instructors_/$instructorId'
      path: '/instructors/$instructorId'
      fullPath: '/instructors/$instructorId'
      preLoaderRoute: typeof AuthInstructorsInstructorIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/courses_/$courseId': {
      id: '/_auth/courses_/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof AuthCoursesCourseIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthCoursesRoute: typeof AuthCoursesRoute
  AuthCreateCourseRoute: typeof AuthCreateCourseRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthInstructorsRoute: typeof AuthInstructorsRoute
  AuthStudentsRoute: typeof AuthStudentsRoute
  AuthCoursesCourseIdRoute: typeof AuthCoursesCourseIdRoute
  AuthInstructorsInstructorIdRoute: typeof AuthInstructorsInstructorIdRoute
  AuthStudentsStudentIdRoute: typeof AuthStudentsStudentIdRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthCoursesRoute: AuthCoursesRoute,
  AuthCreateCourseRoute: AuthCreateCourseRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthInstructorsRoute: AuthInstructorsRoute,
  AuthStudentsRoute: AuthStudentsRoute,
  AuthCoursesCourseIdRoute: AuthCoursesCourseIdRoute,
  AuthInstructorsInstructorIdRoute: AuthInstructorsInstructorIdRoute,
  AuthStudentsStudentIdRoute: AuthStudentsStudentIdRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
